module Kumogata; end
require 'kumogata/version'

require 'aws-sdk'
require 'base64'
require 'coderay'
require 'diffy'
require 'dslh'
require 'hashie'
require 'highline/import'
require 'json'
require 'logger'
require 'net/ssh'
require 'open-uri'
require 'open3'
require 'optparse'
require 'singleton'
require 'strscan'
require 'term/ansicolor'
require 'uuidtools'

require 'kumogata/argument_parser'
require 'kumogata/client'
require 'kumogata/crypt'
require 'kumogata/ext/coderay_ext'
require 'kumogata/ext/json_ext'
require 'kumogata/ext/string_ext'
require 'kumogata/logger'
require 'kumogata/post_processing'
require 'kumogata/utils'
